apiVersion: v1
kind: Service
metadata:
  name: consumer2
  labels:
    app: consumer2
    k8s-app: prometheus
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: consumer2
  type: ClusterIP