apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
        k8s-app: prometheus
    spec:
      containers:
      - name: consumer
        image: dreamstream/consumer:273
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: CONSUMER_GROUP
          value: MyConsumerGroup