apiVersion: v1
kind: Service
metadata:
  name: consumer-kafka-external
  labels:
    app: consumer-kafka
spec:
  ports:
  - port: 80
    name: web
    nodePort: 30021
  selector:
    app: consumer-kafka
  type: NodePort