apiVersion: v1
kind: Service
metadata:
  name: consumer-kafka
  labels:
    app: consumer-kafka
    k8s-app: prometheus
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: consumer-kafka
  type: ClusterIP